clear;
close all;

%
% Name :
%   ray_test4.m
%
% Purpose :
%   Example of using raytrace_2d (WGS84 ellispoidal Earth)for a set of rays with
%   the same launch direction at different frequencies. Ray trajectories are
%   plotted over the ionosphere which has been generated by IRI 2020.
%
% Calling sequence :
%   ray_test4
%
% Inputs :
%   None
%
% Outputs :
%   None
%
% Change log:
%   V1.0  M.A. Cervera  09/06/2016
%     Initial Version
%
%   V1.1  M.A. Cervera  16/05/2023
%      Updated to use IRI2020
%


%
% setup general stuff
%
% My birthday: August 15, 2003. Using 7am for the time.
UT = [2003 8 15 7 0];        % UT - year, month, day, hour, minute
R12 = 100;                   % R12 index
speed_of_light = 2.99792458e8;

% ray_bear = 324.7;

transmit = "VA";
% transmit = "TX";

% switch statement to make it easier for me to change transmitters
switch transmit
    case "VA"
        % Chesapeake, VA
        origin_lat = 36.77;          % latitude of the start point of ray
        origin_long = -76.29;         % longitude of the start point of ray
    case "TX"
        % Corpus Christi, TX
        origin_lat = 27.80;          % latitude of the start point of ray
        origin_long = -97.40;         % longitude of the start point of ray
end

% Auburn, AL
receiver_lat = 32.61;          % latitude of the receiver
receiver_long = -85.48;         % longitude of the receiver

% calculate bearing and range
[dist_m, ray_bear] = latlon2raz(receiver_lat,receiver_long,origin_lat,origin_long);
dist_km = dist_m/1000;
fprintf('Target Range: %.2f km | Bearing: %.2f deg\n', dist_km, ray_bear);
% committing here because bearing and range are correct (per Google Earth)

% these are leftover from ray_test4.m
doppler_flag = 1;            % generate ionosphere 5 minutes later so that
                             % Doppler shift can be calculated
irregs_flag = 0;             % no irregularities - not interested in 
                             % Doppler spread or field aligned irregularities
kp = 0;                      % kp not used as irregs_flag = 0. Set it to a 
                             % dummy value 

fprintf( ...
  '\nExample of 2D numerical raytracing for a ray at different frequencies\n\n')

%
% generate ionospheric, geomagnetic and irregularity grids
%
max_range = 10000;      % maximum range for sampling the ionosphere (km)
num_range = 201;        % number of ranges (must be < 2000)
range_inc = max_range ./ (num_range - 1);  % range cell size (km)

start_height = 0 ;      % start height for ionospheric grid (km)
height_inc = 3;         % height increment (km)
num_heights = 200;      % number of  heights (must be < 2000)

clear iri_options
iri_options.Ne_B0B1_model = 'Bil-2000'; % this is a non-standard setting for 
                                        % IRI but is used as an example
tic
fprintf('Generating ionospheric grid... ')
[iono_pf_grid, iono_pf_grid_5, collision_freq, irreg] = ...
    gen_iono_grid_2d(origin_lat, origin_long, R12, UT, ray_bear, ...
                     max_range, num_range, range_inc, start_height, ...
		     height_inc, num_heights, kp, doppler_flag, 'iri2020', ...
		     iri_options);
toc
 

% convert plasma frequency grid to  electron density in electrons/cm^3
iono_en_grid = iono_pf_grid.^2 / 80.6164e-6;
iono_en_grid_5 = iono_pf_grid_5.^2 / 80.6164e-6;


%
% Example 1 - rays of different frequency with same launch elevation
%

% first call to raytrace so pass in the ionospheric and geomagnetic grids 
freqs = 1:0.1:10; % 1-10 MHz in 0.1 MHz increments
elevs = ones(size(freqs)).*20;
num_elevs = length(elevs);
tol = 1e-7;          % ODE tolerance
nhops = 2;
tic
fprintf('Generating %d 2D NRT rays ...', num_elevs);
[ray_data, ray_path_data] = ...
    raytrace_2d(origin_lat, origin_long, elevs, ray_bear, freqs, nhops, ...
             tol, irregs_flag, iono_en_grid, iono_en_grid_5, ...
	     collision_freq, start_height, height_inc, range_inc, irreg);
toc

% plot the rays and ionosphere
figure(1)
UT_str = [num2str(UT(3)) '/' num2str(UT(2)) '/' num2str(UT(1)) '  ' ...
          num2str(UT(4), '%2.2d') ':' num2str(UT(5), '%2.2d') 'UT'];
elev_str = [num2str(elevs(1)) ' deg'];
R12_str = num2str(R12);
lat_str = num2str(origin_lat);
lon_str = num2str(origin_long);
bearing_str = num2str(ray_bear);
fig_str = [UT_str '   elevation = ' elev_str '   R12 = ' R12_str '   lat = ' ...
           lat_str ', lon = ' lon_str ', bearing = ' bearing_str];
set(gcf, 'name', fig_str)
start_range = 0;
end_range = 2500;
end_range_idx = fix((end_range-start_range) ./ range_inc) + 1;
start_ht = start_height;
start_ht_idx = 1;
end_ht = 450;
end_ht_idx = fix(end_ht ./ height_inc) + 1;
iono_pf_subgrid = iono_pf_grid(start_ht_idx:end_ht_idx, 1:end_range_idx);
plot_ray_iono_slice(iono_pf_subgrid, start_range, end_range, range_inc, ...
    start_ht, end_ht, height_inc, ray_path_data, 'color', [1, 1, 0.99], ...
    'linewidth', 2);

set(gcf,'units','normal')
pos = get(gcf,'position');
pos(2) = 0.55;
set(gcf,'position', pos)

% uncomment the following to print figure to hi-res ecapsulated postscript
% and PNG files
set(gcf, 'paperorientation', 'portrait')
set(gcf, 'paperunits', 'cent', 'paperposition', [0 0 61 18])
set(gcf, 'papertype', 'a4') 
% print -depsc2 -loose -opengl test.ps 
% print -dpng test.png


fprintf('\n')